language: node_js
node_js:
  - "stable"
script:
  - npm run coverage
before_install:
  - npm install istanbul@0
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search
